name: Release-terraform

on:
  push:
    branches:
      # - master # creates a pre-release
      - nowhere
  # release:
  #   types:
  #     - released # does not include pre-release
  # workflow_dispatch:
  #   inputs:
  #     branch:
  #       description: "Branch to set as prerelease"
  #       required: false
  #       default: "master"

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GOARCH: "amd64"
            GOOS: "linux"
          - GOARCH: "386"
            GOOS: "linux"
          - GOARCH: "arm64"
            GOOS: "linux"
          - GOARCH: "amd64"
            GOOS: "darwin"
          - GOARCH: "arm64"
            GOOS: "darwin"
          - GOARCH: "amd64"
            GOOS: "windows"
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@master
      - name: Cache Go Build and Modules
        id: cache-go-modules
        uses: actions/cache@v2
        with:
          path: |
            .cache-modules
            .cache-go-build
          key: ${{ runner.os }}-terraform-1.0.1-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum') }}-v2
          restore-keys: |
            ${{ runner.os }}-terraform-1.0.1-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-
      - name: Get Dependencies
        if: steps.cache-go-modules.outputs.cache-hit != 'true'
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: dependencies
          src-dir: terraform-1.0.1
      - name: Go Build
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: build
          src-dir: terraform-1.0.1
      - name: Go Test
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: test
          src-dir: terraform-1.0.1
      - name: Release
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: release
          src-dir: terraform-1.0.1
          gh-token: ${{ secrets.GH_TOKEN }}
