name: Release-Test-Remote-Repo

on:
  workflow_dispatch:
    inputs:
      target-url:
        default: https://github.com/hashicorp/terraform/archive/refs/tags/v1.0.2.tar.gz
        description: ""
        required: true
      use-bearer-token:
        default: "false"
        description: Use GH_TOKEN or GITHUB_TOKEN
        required: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Get src-dir path
        id: get-src-dir-path
        env:
          TARGET_URL: ${{ github.event.inputs.target-url }}
        run: scripts/workflow_dispatch.sh
      - name: Cache Go Build
        id: cache-go-build
        uses: actions/cache@v2
        with:
          path: |
            .cache-go-build
          key: ${{ runner.os }}-go-build-test-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
          restore-keys: |
            ${{ runner.os }}-go-build-test-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
      - name: Cache Go Modules
        id: cache-go-modules
        uses: actions/cache@v2
        with:
          path: |
            .cache-modules
          key: ${{ runner.os }}-go-modules-test-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
          restore-keys: |
            ${{ runner.os }}-go-modules-test-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
      - name: Get Dependencies
        if: steps.cache-go-modules.outputs.cache-hit != 'true'
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: dependencies
          src-dir: ${{ steps.get-src-dir-path.outputs.SRC_DIR }}
          project-name: workflow_dispatch
      - name: Go Test
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: test
          src-dir: ${{ steps.get-src-dir-path.outputs.SRC_DIR }}
          project-name: workflow_dispatch
      - name: Upload Test Results As Artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test_report
          path: test_report.html
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GOARCH: "amd64"
            GOOS: "linux"
          - GOARCH: "386"
            GOOS: "linux"
          - GOARCH: "arm64"
            GOOS: "linux"
          - GOARCH: "amd64"
            GOOS: "darwin"
          - GOARCH: "amd64"
            GOOS: "windows"
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@master
      - name: Get src-dir path
        id: get-src-dir-path
        env:
          TARGET_URL: ${{ github.event.inputs.target-url }}
        run: scripts/workflow_dispatch.sh
      - name: Cache Go Build
        id: cache-go-build
        uses: actions/cache@v2
        with:
          path: |
            .cache-go-build
          key: ${{ runner.os }}-go-build-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
          restore-keys: |
            ${{ runner.os }}-go-build-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
      - name: Cache Go Modules
        id: cache-go-modules
        uses: actions/cache@v2
        with:
          path: |
            .cache-modules
          key: ${{ runner.os }}-go-modules-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
          restore-keys: |
            ${{ runner.os }}-go-modules-${{ matrix.GOOS }}-${{ matrix.GOARCH }}-${{ hashFiles('**/go.sum') }}-${{ steps.get-src-dir-path.outputs.SRC_DIR }}-v3
      - name: Get Dependencies
        if: steps.cache-go-modules.outputs.cache-hit != 'true'
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: dependencies
          src-dir: ${{ steps.get-src-dir-path.outputs.SRC_DIR }}
          project-name: workflow_dispatch
      - name: Go Build
        id: go-build
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: build
          src-dir: ${{ steps.get-src-dir-path.outputs.SRC_DIR }}
          project-name: workflow_dispatch
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.go-build.outputs.artifact-name }}
          path: ${{ steps.go-build.outputs.artifact-full-path }}
  release:
    name: Release
    needs:
      - test
      - build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - GOARCH: "amd64"
            GOOS: "linux"
          - GOARCH: "386"
            GOOS: "linux"
          - GOARCH: "arm64"
            GOOS: "linux"
          - GOARCH: "amd64"
            GOOS: "darwin"
          - GOARCH: "amd64"
            GOOS: "windows"
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@master # This is for getting the current commit SHA
      - uses: actions/download-artifact@v2
        name: Download Build Artifact
        with:
          name: "${{ matrix.GOOS }}-${{ matrix.GOARCH }}-workflow_dispatch"
      - name: GitHub Release
        uses: unfor19/release-action/golang/1.16@master
        with:
          action: release
          project-name: workflow_dispatch
          gh-token: ${{ secrets.GH_TOKEN }}
